import { User, Video } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user_1',
    username: 'cyberpunk_vibes',
    displayName: 'Sora Park',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    bio: 'Visual designer exploring Tokyo nights 🌌 Future is now. #cyberpunk',
    followersCount: 342000,
    followingCount: 420,
    postsCount: 142,
    isFollowing: false,
    isVerified: true,
  },
  {
    id: 'user_2',
    username: 'skate_pro',
    displayName: 'Marcus Vance',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    bio: 'Professional skateboarder | LA 🛹 Filming every day. Collabs: DM me',
    followersCount: 85300,
    followingCount: 310,
    postsCount: 88,
    isFollowing: true,
  },
  {
    id: 'user_3',
    username: 'neon_dancer',
    displayName: 'Alex Rivera',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    bio: 'Movement artist. Expressing thoughts through dance & neon glow 💃🕺',
    followersCount: 120500,
    followingCount: 195,
    postsCount: 65,
    isFollowing: false,
  },
  {
    id: 'user_4',
    username: 'sound_synth',
    displayName: 'Luna Thorne',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    bio: 'Analogue synthesizers & ambient loops. Audio engineer 🎛️🎧✨',
    followersCount: 210000,
    followingCount: 520,
    postsCount: 198,
    isFollowing: false,
    isVerified: true,
  },
  {
    id: 'user_5',
    username: 'city_runner',
    displayName: 'Maya Lin',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    bio: 'Run the city, chase the sun. Sunset seeker & fitness coach 🏃‍♀️🌆',
    followersCount: 94100,
    followingCount: 280,
    postsCount: 112,
    isFollowing: true,
  }
];

export const INITIAL_VIDEOS: Video[] = [
  {
    id: 'video_1',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    creator: INITIAL_USERS[0],
    description: 'Neon dreams in the heart of Shibuya. Finding the quiet corners under the glowing signs 🏮✨',
    musicName: 'Midnight Tokyo Vibes',
    musicArtist: 'Sora Park Original Audio',
    likesCount: 24500,
    commentsCount: 342,
    sharesCount: 1820,
    viewsCount: 189000,
    isLiked: false,
    isSaved: false,
    tags: ['cyberpunk', 'tokyonight', 'neonvibes', 'aesthetic'],
    timestamp: '2h ago',
  },
  {
    id: 'video_2',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    creator: INITIAL_USERS[1],
    description: 'Sticking the landing at golden hour. Keep pushing, no matter how many times you fall! 🛹🌅',
    musicName: 'Skater Punk Jam',
    musicArtist: 'The Offbeats',
    likesCount: 12400,
    commentsCount: 198,
    sharesCount: 520,
    viewsCount: 78000,
    isLiked: true,
    isSaved: false,
    tags: ['skater', 'streetwear', 'lifestyle', 'skateparks'],
    timestamp: '5h ago',
  },
  {
    id: 'video_3',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    creator: INITIAL_USERS[2],
    description: 'Freestyling with the light bars. Just letting the rhythm dictate the flow tonight ⚡🕺',
    musicName: 'Future Funk Wave',
    musicArtist: 'Alex Rivera',
    likesCount: 38900,
    commentsCount: 561,
    sharesCount: 2400,
    viewsCount: 320000,
    isLiked: false,
    isSaved: true,
    tags: ['dance', 'freestyle', 'neonlight', 'streetdance'],
    timestamp: '1d ago',
  },
  {
    id: 'video_4',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    creator: INITIAL_USERS[3],
    description: 'Modulating the frequency waves. Crafting a cozy ambient loop for a rainy evening 🌧️🎛️🎹',
    musicName: 'Cozy Rain Ambient Loop',
    musicArtist: 'Luna Thorne',
    likesCount: 18100,
    commentsCount: 215,
    sharesCount: 1200,
    viewsCount: 145000,
    isLiked: false,
    isSaved: false,
    tags: ['synthesizer', 'ambientmusic', 'modular', 'lofivibes'],
    timestamp: '2d ago',
  },
  {
    id: 'video_5',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    creator: INITIAL_USERS[4],
    description: 'Nothing beats running through the empty golden streets after a long work day 🏃‍♀️🌆🧡',
    musicName: 'Golden Hour Run (160 BPM)',
    musicArtist: 'Aesthetic Beats',
    likesCount: 9320,
    commentsCount: 89,
    sharesCount: 142,
    viewsCount: 45000,
    isLiked: false,
    isSaved: false,
    tags: ['running', 'sunset', 'wellness', 'cardio', 'health'],
    timestamp: '3d ago',
  }
];

export const INITIAL_COMMENTS = [
  {
    id: 'comment_1',
    videoId: 'video_1',
    userId: 'user_2',
    username: 'skate_pro',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    text: 'This visual color grading is insane! What camera did you use?',
    timestamp: '1h ago',
    likesCount: 42,
    isLiked: false,
  },
  {
    id: 'comment_2',
    videoId: 'video_1',
    userId: 'user_4',
    username: 'sound_synth',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    text: 'Matches so well with synthwave tracks! 🔥',
    timestamp: '30m ago',
    likesCount: 12,
    isLiked: false,
  },
  {
    id: 'comment_3',
    videoId: 'video_2',
    userId: 'user_1',
    username: 'cyberpunk_vibes',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    text: 'Clean landing dude! Skatepark looks empty, is it early morning?',
    timestamp: '4h ago',
    likesCount: 28,
    isLiked: true,
  },
  {
    id: 'comment_4',
    videoId: 'video_3',
    userId: 'user_5',
    username: 'city_runner',
    userAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    text: 'Wow, those dance shapes are perfect! Full-body control is amazing.',
    timestamp: '12h ago',
    likesCount: 54,
    isLiked: false,
  }
];
